project:
  type: book
  output-dir: docs

lang: fr

book:
  title: "Lignes de vie"
  author: "Christophe Ambroise"
  date: "7/20/2025"
  chapters:
    - index.qmd
    - Ambroise-Doullens.qmd
    - AJJ-Ambroise.qmd
    - Ambroise-Hissette.qmd
    - Documents-transcriptions.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
  docx:
    toc: true
    number-sections: true
editor: visual

