<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr" xml:lang="fr"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; Aline Julienne Joséphine Ambroise (1837-1865) – Fragments d’une filiation France-Allemagne, de l'origine de la famille Ambroise</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Ambroise-Hissette.html" rel="next">
<link href="./Ambroise-Doullens.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-626149efe8f5d16e1d391ba177679bf0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Pas de résultats",
    "search-matching-documents-text": "documents trouvés",
    "search-copy-link-title": "Copier le lien vers la recherche",
    "search-hide-matches-text": "Cacher les correspondances additionnelles",
    "search-more-match-text": "correspondance de plus dans ce document",
    "search-more-matches-text": "correspondances de plus dans ce document",
    "search-clear-button-title": "Effacer",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuler",
    "search-submit-button-title": "Envoyer",
    "search-label": "Recherche"
  }
}</script>
<script src="site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="site_libs/quarto-diagram/mermaid.css" rel="stylesheet">


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Basculer la barre latérale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./AJJ-Ambroise.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Aline Julienne Joséphine Ambroise (1837-1865)</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Basculer la barre latérale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Recherche" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Fragments d’une filiation France-Allemagne, de l’origine de la famille Ambroise</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Recherche"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./patronyme-ambroise.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Le patronyme Ambroise</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ambroise-Doullens.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">La famille Ambroise à Doullens dans la Somme (1600-1850)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./AJJ-Ambroise.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Aline Julienne Joséphine Ambroise (1837-1865)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ambroise-Hissette.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Alfred Ambroise (1861- ), Catherine Hissette (1868- ) et leurs enfants</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Gillet-Anchier.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Marie Gillet (1852–1941) et Charles Anchier (1852–1935), et leurs enfants</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Anchier-Margerie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">René Anchier, Fernande Marguerie (1889-1930) et leurs enfants</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Documents-transcriptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Documents et transcriptions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Références</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table des matières</h2>
   
  <ul>
  <li><a href="#les-métiers-de-julienne-et-ses-enfants" id="toc-les-métiers-de-julienne-et-ses-enfants" class="nav-link active" data-scroll-target="#les-métiers-de-julienne-et-ses-enfants"><span class="header-section-number">3.1</span> Les métiers de Julienne et ses enfants</a></li>
  <li><a href="#chronologie" id="toc-chronologie" class="nav-link" data-scroll-target="#chronologie"><span class="header-section-number">3.2</span> Chronologie</a>
  <ul class="collapse">
  <li><a href="#années-18301840-modernisation-progressive" id="toc-années-18301840-modernisation-progressive" class="nav-link" data-scroll-target="#années-18301840-modernisation-progressive"><span class="header-section-number">3.2.1</span> Années 1830–1840 — Modernisation progressive</a></li>
  <li><a href="#années-18401850-arrivée-des-chemins-de-fer" id="toc-années-18401850-arrivée-des-chemins-de-fer" class="nav-link" data-scroll-target="#années-18401850-arrivée-des-chemins-de-fer"><span class="header-section-number">3.2.2</span> Années 1840–1850 — Arrivée des chemins de fer</a></li>
  <li><a href="#révolution-et-période-incertaine" id="toc-révolution-et-période-incertaine" class="nav-link" data-scroll-target="#révolution-et-période-incertaine"><span class="header-section-number">3.2.3</span> 1848–1851 — Révolution et période incertaine</a></li>
  <li><a href="#second-empire-et-prospérité-régionale" id="toc-second-empire-et-prospérité-régionale" class="nav-link" data-scroll-target="#second-empire-et-prospérité-régionale"><span class="header-section-number">3.2.4</span> 1850–1860 — Second Empire et prospérité régionale</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="ajj" class="quarto-section-identifier"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Aline Julienne Joséphine Ambroise (1837-1865)</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell" data-fig-width="4" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-arbre-ambroise" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-arbre-ambroise-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<pre class="mermaid mermaid-js" data-label="fig-arbre-ambroise">graph TD
  P1[Pierre Joseph Théophile Ambroise&lt;br&gt;1810–1838]
  P2[Aurore Élisabeth Joséphine Lecointe&lt;br&gt;1807- ]  
  P1 --&gt; A[Aline Jullienne Joséphine Ambroise&lt;br&gt;1837–1865]
  P2 --&gt; A
  A --&gt; Jn[Jeanne&lt;br&gt;1855‑?]
  A --&gt; Cl[Claire&lt;br&gt;1857‑?]
  A --&gt; MH[Marthe Héloïse&lt;br&gt;1858‑?]
  A --&gt; VS[Victoria Sophie&lt;br&gt;1860‑?]
  A --&gt; Al[Alfred&lt;br&gt;1861‑?]
  A --&gt; Ad[Adrienne&lt;br&gt;1863‑1902]
  A --&gt; F[Florimond&lt;br&gt;1865‑?]
</pre>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-arbre-ambroise-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.1: Arbre simplifié : Aline Julienne Joséphine et ses proches
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Aline Julienne Joséphine</strong> est née à Doullens le 3 mai 1837. Elle fut une femme pauvre — ou, au mieux, modeste — du XIXe siècle. Une femme dont l’histoire ne conserve presque rien, sinon quelques lignes sèches sur les registres d’état civil. Et pourtant, elle tient une place essentielle dans notre lignée Ambroise. <strong>C’est elle qui a transmis le nom, seule, à chacun de ses enfants</strong>. Aucun homme n’a reconnu ces naissances. Aucun père n’a laissé sa trace.</p>
<p>Son père, Pierre Joseph Théophile Ambroise (1810-1838), était tailleur d’habits à Doullens, comme ses deux frères et comme tant d’Ambroise avant lui, depuis George Ambroise (1635-1709), maître tailleur dans la même ville dès le XVIIe siècle. Sa mère, Aurore Élisabeth Joséphine Lecointe (1807-), venait d’un milieu d’artisans : sœur d’un serrurier, belle-sœur d’un boulanger.</p>
<p>Ils se marièrent en 1832. Pierre Joseph avait 22 ans. Il mourut cinq ans plus tard, à 27 ans, laissant derrière lui une fillette de un an et une veuve de 30 ans. À Doullens, dans les années 1830, lorsqu’un homme mourait si jeune, la famille basculait immédiatement dans la précarité. Il n’existait ni secours public, ni pension. La survie dépendait alors des solidarités familiales, des voisins, de ce que chacun pouvait donner ou faire.</p>
<p>Julienne quitta Doullens. Elle partit pour Amiens, puis Paris. Peut-être poussée par une grossesse, peut-être par le désir de recommencer. Elle y vécut une vie rude. Les métiers qu’elle exerça — piqueuse de bottines, lingère — parlent d’eux-mêmes.</p>
<p>Elle donna naissance à au moins <strong>sept enfants, tous naturels</strong>, tous enregistrés sous son seul nom. Le premier, Jeanne, naît à Doullens en 1855. Julienne a alors dix-huit ans. Jeanne deviendra brumisseuse et épousera plus tard un cocher, Félix Pierre Dériot, à Paris. En 1857, à Amiens, naît Claire. Puis Marthe Héloïse, en 1858, également à Amiens. En 1860, Victoria Sophie vient au monde à Paris. Alfred — mon ancêtre — naît en 1861, suivi d’Adrienne en 1863, puis de Florimond en 1865.</p>
<p>Tous ces enfants sans père déclaré. Était-ce un choix, une contrainte, un silence imposé ? On ne le saura jamais. Ce que l’on sait, c’est qu’à la mort d’Aline, le 24 octobre 1865, à seulement 28 ans, la fratrie est dispersée. Enterrée à Ivry-sur-Seine, elle disparaît du paysage. Plus tard, Alfred et Florimond, au moment de se marier, diront n’avoir jamais eu de nouvelles de leur mère. Preuve probable qu’ils ont été placés très jeunes.</p>
<p>Cette jeune femme, seule dans Paris, vivant de métiers difficiles, changeant de villes, pour terminer sur Paris, sans soutien durable, incarne une force silencieuse. Elle n’a laissé ni portrait, ni lettre — seulement des naissances (7 enfants en 10 ans) et une mort précoce.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="AJJ-Ambroise_files/figure-html/carte-france-villes-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption>Carte de France avec Doullens, Amiens et Paris</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Images/Doullens.jpg" class="img-fluid figure-img" width="554"></p>
<figcaption>La rue du Bourg, avec son beffroi et les maisons alignées le long du commerce central — un quartier vivant dès le XIXᵉ siècle.</figcaption>
</figure>
</div>
</div>
</div>
<section id="les-métiers-de-julienne-et-ses-enfants" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="les-métiers-de-julienne-et-ses-enfants"><span class="header-section-number">3.1</span> Les métiers de Julienne et ses enfants</h2>
<p>Les métiers qu’exerça Aline Julienne Joséphine — piqueuse de bottines, lingère — disent à eux seuls la condition qui fut la sienne. La <strong>piqueuse de bottines</strong>, métier répandu à Paris dans les années 1850–1860, intervenait dans la fabrication de chaussures, souvent en atelier ou à domicile, sur commande. Elle assemblait, à la main ou sur des machines rudimentaires, les pièces de cuir, de toile ou de drap qui formaient la tige de la chaussure. Ce travail exigeait de la minutie, une bonne vue, et une cadence soutenue, car les rémunérations étaient à la pièce, et faibles. Ce métier apparaît dans les recensements parisiens dès le début du Second Empire, et reflète l’essor de la production artisanale pré-industrielle, avant la mécanisation complète de la chaussure dans les années 1870.</p>
<p><strong>Lingère</strong> était un métier plus ancien, déjà bien établi au XVIIIᵉ siècle. Dans les années 1850–1860, la lingère travaillait à la confection, l’entretien ou la réparation du linge de maison ou de corps: chemises, jupons, cols, draps, mouchoirs. Elle pouvait être employée par une maison bourgeoise, une blanchisserie, ou travailler à son compte. Là encore, c’était un métier de l’ombre, précaire, sous-payé, souvent exercé par des femmes seules ou veuves. Il permettait de survivre, rarement de vivre.</p>
<p>Les enfants de Julienne, tels que le révèlent les archives, ont occupé des métiers modestes. Jeanne, en particulier, fut à la fois journalière et brumisseuse — deux activités féminines emblématiques du labeur discret et précaire du XIXᵉ siècle. Le terme de <strong>brumisseuse</strong>, aujourd’hui disparu, désignait une ouvrière spécialisée dans le tissage ou la préparation d’étoffes très fines appelées « brumes ». Ces tissus légers, destinés à la confection de voilages ou de vêtements délicats, exigeaient un savoir-faire minutieux, exercé soit à domicile, soit dans les manufactures textiles du nord de la France.</p>
<p>Le métier de <strong>journalière</strong>, quant à lui, témoigne d’une condition encore plus exposée à l’aléa économique. Travaillant à la tâche ou à la journée, Jeanne rejoignait chaque matin les rangs silencieux de ces femmes engagées sans contrat stable, souvent pour de petits travaux agricoles ou domestiques, mal rémunérés et saisonniers.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Images/1860-paris-rue-passy.jpg" class="img-fluid figure-img" width="800"></p>
<figcaption>Paris - La rue de Passy dans le XVI° arrondissement de Paris : Avant 1860</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="chronologie" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="chronologie"><span class="header-section-number">3.2</span> Chronologie</h2>
<p>Entre 1837 et 1865, la France connut de profondes mutations politiques, économiques et sociales: d’abord sous la Monarchie de Juillet (1830–1848), puis la Seconde République, et enfin le début du Second Empire (à partir de 1852). Ce fut l’ère de l’industrialisation douce, caractérisée par l’essor du chemin de fer et de l’industrie textile et métallurgique.</p>
<p>À Amiens, ces transformations se traduisirent dès les années 1830 par l’effacement partiel des remparts, la création de boulevards, l’installation d’usines (gaz, abattoirs) et l’arrivée de la ligne Paris–Lille en 1846, puis de la ligne vers Boulogne en 1847–48. La ville devint un centre industriel en plein essor, amorçant un tournant urbanistique.</p>
<p>À Doullens, proche mais plus modeste, l’artisanat rural — tailleurs, tisserands, petits métiers — perdurait, tout en étant progressivement influencé par l’ouverture des gares régionales et les réseaux ferroviaires.</p>
<p>Pour Julienne, née en 1837 et vivant entre Doullens, Amiens et Paris, ce fut un passage du monde artisanal provincial à la vie urbaine. Elle vit défiler les régimes, les gares et les ateliers («piqueuse de bottines», lingère), entre la naissance de sept enfants et une disparition prématurée en 1865. Son parcours reflète à son échelle les bouleversements de la France: rurale, puis industrielle ; provinciale, puis urbaine. Le film de Cédric Klapisch La venue de l’avenir <span class="citation" data-cites="klapisch2025venue">(<a href="references.html#ref-klapisch2025venue" role="doc-biblioref">Klapisch 2025</a>)</span> restitue l’ambiance de l’époque et alimente l’imaginaire que nous pouvons avoir de Julienne.</p>
<section id="années-18301840-modernisation-progressive" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="années-18301840-modernisation-progressive"><span class="header-section-number">3.2.1</span> Années 1830–1840 — Modernisation progressive</h3>
<ul>
<li>1830 : Révolution des Trois Glorieuses, avènement de la Monarchie de Juillet. Des idées libérales circulent aussi à Doullens et Amiens.</li>
<li>À Amiens, vaste chantier de «hausmannisation avant l’heure» :</li>
<li>démolition des remparts, création de boulevards (1830–1848) ;</li>
<li>ouverture de la bibliothèque (1826), de la Caisse d’Épargne (1833), du cimetière de la Madeleine ;</li>
<li>industrialisation naissante, abattoirs (1833), usine à gaz (1836).</li>
</ul>
</section>
<section id="années-18401850-arrivée-des-chemins-de-fer" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="années-18401850-arrivée-des-chemins-de-fer"><span class="header-section-number">3.2.2</span> Années 1840–1850 — Arrivée des chemins de fer</h3>
<ul>
<li>1846 : ligne Paris–Lille, gare d’Amiens (Gare du Nord) inaugurée, suscitant l’ouverture de la ville vers Paris ￼.</li>
<li>1847–1848 : ligne Amiens–Boulogne/St‑Roch ; développement industriel facilité par la « Société industrielle » créée en 1836.</li>
</ul>
</section>
<section id="révolution-et-période-incertaine" class="level3" data-number="3.2.3">
<h3 data-number="3.2.3" class="anchored" data-anchor-id="révolution-et-période-incertaine"><span class="header-section-number">3.2.3</span> 1848–1851 — Révolution et période incertaine</h3>
<ul>
<li>Février 1848 : Révolution de février, IIe République proclamée;</li>
<li>Juin 1848 : insurrection ouvrière à Paris, réprimée violemment (les «Journées de Juin»).</li>
<li>En Picardie, dont Amiens, l’insurrection connaît un certain soutien, et des arbres de la liberté sont plantés.</li>
</ul>
</section>
<section id="second-empire-et-prospérité-régionale" class="level3" data-number="3.2.4">
<h3 data-number="3.2.4" class="anchored" data-anchor-id="second-empire-et-prospérité-régionale"><span class="header-section-number">3.2.4</span> 1850–1860 — Second Empire et prospérité régionale</h3>
<ul>
<li>1851 : Coup d’État de Louis-Napoléon, début du Second Empire — engouement modéré en Picardie.</li>
<li>1853 : Napoléon III visite Amiens, signe de modernité.</li>
<li>1855–1867 : Amiens s’enrichit : musée de Picardie, extension du réseau ferroviaire vers Laon et Rouen.</li>
<li>À Doullens et alentours, l’essor du rail commence à transformer les échanges mais l’artisanat (tailleur, mulquinerie) reste intact.</li>
</ul>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-klapisch2025venue" class="csl-entry" role="listitem">
Klapisch, Cédric, réal. 2025. <em>La Venue de l’avenir</em>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copié");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copié");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Ambroise-Doullens.html" class="pagination-link" aria-label="La famille Ambroise à Doullens dans la Somme (1600-1850)">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">La famille Ambroise à Doullens dans la Somme (1600-1850)</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Ambroise-Hissette.html" class="pagination-link" aria-label="Alfred Ambroise (1861- ), Catherine Hissette (1868- ) et leurs enfants">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Alfred Ambroise (1861- ), Catherine Hissette (1868- ) et leurs enfants</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>