<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr" xml:lang="fr"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; René Anchier, Fernande Marguerie (1889-1930) et leurs enfants – Fragments d’une filiation France-Allemagne, de l'origine de la famille Ambroise</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Documents-transcriptions.html" rel="next">
<link href="./Gillet-Anchier.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-626149efe8f5d16e1d391ba177679bf0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Pas de résultats",
    "search-matching-documents-text": "documents trouvés",
    "search-copy-link-title": "Copier le lien vers la recherche",
    "search-hide-matches-text": "Cacher les correspondances additionnelles",
    "search-more-match-text": "correspondance de plus dans ce document",
    "search-more-matches-text": "correspondances de plus dans ce document",
    "search-clear-button-title": "Effacer",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuler",
    "search-submit-button-title": "Envoyer",
    "search-label": "Recherche"
  }
}</script>
<script src="site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="site_libs/quarto-diagram/mermaid.css" rel="stylesheet">


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Basculer la barre latérale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Anchier-Margerie.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">René Anchier, Fernande Marguerie (1889-1930) et leurs enfants</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Basculer la barre latérale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Recherche" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Fragments d’une filiation France-Allemagne, de l’origine de la famille Ambroise</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Recherche"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./patronyme-ambroise.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Le patronyme Ambroise</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ambroise-Doullens.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">La famille Ambroise à Doullens dans la Somme (1600-1850)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./AJJ-Ambroise.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Aline Julienne Joséphine Ambroise (1837-1865)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ambroise-Hissette.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Alfred Ambroise (1861- ), Catherine Hissette (1868- ) et leurs enfants</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Gillet-Anchier.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Marie Gillet (1852–1941) et Charles Anchier (1852–1935), et leurs enfants</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Anchier-Margerie.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">René Anchier, Fernande Marguerie (1889-1930) et leurs enfants</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Documents-transcriptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Documents et transcriptions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Références</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table des matières</h2>
   
  <ul>
  <li><a href="#rené-anchier-peintre-à-bar-le-duc" id="toc-rené-anchier-peintre-à-bar-le-duc" class="nav-link active" data-scroll-target="#rené-anchier-peintre-à-bar-le-duc"><span class="header-section-number">6.1</span> René Anchier, peintre à Bar-le-Duc</a></li>
  <li><a href="#fernande-margerie" id="toc-fernande-margerie" class="nav-link" data-scroll-target="#fernande-margerie"><span class="header-section-number">6.2</span> Fernande Margerie</a>
  <ul class="collapse">
  <li><a href="#linternement-de-fernande" id="toc-linternement-de-fernande" class="nav-link" data-scroll-target="#linternement-de-fernande"><span class="header-section-number">6.2.1</span> L’internement de Fernande</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="anchier-marguerie" class="quarto-section-identifier"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">René Anchier, Fernande Marguerie (1889-1930) et leurs enfants</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="rené-anchier-peintre-à-bar-le-duc" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="rené-anchier-peintre-à-bar-le-duc"><span class="header-section-number">6.1</span> René Anchier, peintre à Bar-le-Duc</h2>
<div class="cell" data-fig-width="6" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-arbre-anchier" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-arbre-anchier-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<pre class="mermaid mermaid-js" data-label="fig-arbre-anchier">graph TD
  C1[Charles François Anchier&lt;br&gt;1852-]
  G1[Marie Berthe Gillet&lt;br&gt;1852-]
  Mariage[Mariage]
  F1[Marguerite Marie Elisa &lt;br&gt;1877–1908]
  F2[Jeanne Marie Berthe &lt;br&gt;1880–]
  F3[Léon Marie Fernand &lt;br&gt;1882–]
  F4[Léon Marie René &lt;br&gt;1884–1885]
  F5[**Charles Léon René Anchier**&lt;br&gt;1886–1936&lt;br&gt;**Peintre**]
  F6[Félicien Gaston Marie &lt;br&gt;1888–]
  F7[Berthe Marie Thérèse &lt;br&gt;1890–1890]
  F8[Henri Marie Joseph &lt;br&gt;1892–]

  C1 --&gt; Mariage
  G1 --&gt; Mariage
  Mariage --&gt; F1
  Mariage --&gt; F2
  Mariage --&gt; F3
  Mariage --&gt; F4
  Mariage --&gt; F5
  Mariage --&gt; F6
  Mariage --&gt; F7
  Mariage --&gt; F8
</pre>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-arbre-anchier-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.1: Branche familiale de Charles Léon René Anchier (1886–1936)
</figcaption>
</figure>
</div>
</div>
</div>
<p>René Anchier naît au sein d’une famille nombreuse à Bar-le-Duc. Il est l’un des enfants de <strong>Marie Gillet</strong>, dite Berthe, et de <strong>Charles Anchier</strong>, comptable. Le couple a eu huit enfants, dont René fut le troisième. La famille vivait dans une atmosphère lettrée et pieuse, entre vie de maison et éveil aux grands bouleversements du siècle.</p>
<p>Le 3 janvier 1914, René épouse <strong>Fernande Marie Renée Marguerie</strong>, issue d’une famille cultivée mais marquée par de nombreux deuils précoces. La Première Guerre Mondiale éclate quelques mois plus tard.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Images/mariage-anchier-marguerie.jpeg" class="img-fluid figure-img" width="2574"></p>
<figcaption>Mariage de René Anchier et Fernande Marguerie</figcaption>
</figure>
</div>
</div>
</div>
<p>René Anchier subit un parcours militaire marqué par la rigueur et les blessures de guerre (<a href="Documents-transcriptions.html#fiche-militaire-rene-anchier">fiche matriculaire de René Anchier</a>).</p>
<p>Incorporé en tant que <strong>chasseur de deuxième classe</strong> au <strong>19ᵉ régiment des bataillons de chasseurs à pied</strong>, il part en disponibilité en septembre 1909 après l’obtention d’un <strong>certificat de bonne conduite</strong>, puis est rappelé dès août 1914 – 8 mois après son mariage – pour rejoindre le <strong>9ᵉ régiment du Génie</strong>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Images/1909-rene-anchier.jpg" class="img-fluid figure-img" width="588"></p>
<figcaption>René Anchier lors de sa première incorporation (service militaire).</figcaption>
</figure>
</div>
</div>
</div>
<p>René est blessé à Aigny, dans la Marne, le 21 août 1914, touché à la fesse gauche par une balle, sans doute lors des premiers combats de la bataille des frontières. Cette blessure laissera des séquelles durables et entraîne une inaptitude temporaire reconnue par la Commission de réforme d’Aquitaine en <strong>janvier 1916</strong>. Classé en <strong>service auxiliaire</strong> pour <strong>plicature dorsolombaire de nature psychonévrosique</strong>, liée à sa blessure d’août 1914. Il est muté au <strong>9ᵉ Régiment du Génie</strong> le 21 octobre 1918, à quelques semaines de l’armistice et <strong>participe probablement à des travaux de fortification ou de réparation dans l’Aisne ou en Belgique</strong>. Il est démobilisé en mars 1919 et retourne vivre à Bar-le-Duc, marqué dans son corps et dans son esprit par cette guerre.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Anchier-Margerie_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption>Recto et verso d’une carte postale envoyée à Fernande par René, qui lui déclare son amour pour la vie… .</figcaption>
</figure>
</div>
</div>
</div>
<p>René et Fernande auront trois enfants: <strong>Marguerite</strong>, née en 1916 pendant la guerre, <strong>Marie-Thérèse</strong>, ma grand-mère, née en 1921, et <strong>Henri</strong>, né en 1923. René exerce le métier de peintre à Bar-le-Duc.</p>
<p>Hélas, Fernande tombe gravement malade peu après la naissance de Marie-Thérèse. Elle est internée à partir de 1921, puis définitivement en 1923. René se retrouve seul avec ses trois enfants et les confie à sa propre mère, <strong>Marie Gillet</strong>, qui les élèvera.</p>
<p>C’est dans ce foyer que grandira ma grand-mère Marie-Thérèse, marquée à jamais par l’absence de sa mère et le silence qui l’entourait.</p>
<p>La vie de René Anchier, décédé prématurément le 5 avril 1936 à l’âge de 50 ans, oscille — comme celle de tant d’hommes de son époque — entre engagement familial, travail artisanal, expérience de la guerre 14-18 et résilience face aux drames intimes.</p>
</section>
<section id="fernande-margerie" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="fernande-margerie"><span class="header-section-number">6.2</span> Fernande Margerie</h2>
<div class="cell" data-fig-width="6" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-arbre-fernande" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-arbre-fernande-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<pre class="mermaid mermaid-js" data-label="fig-arbre-fernande">graph TD
  P1[Eugénie Julie Marie Hacquin&lt;br&gt;1869‑1895&lt;br&gt;**Décédée à 26 ans**]
  P2[René Alexandre Marguerie&lt;br&gt;1864‑1898&lt;br&gt;**Marchand de vin**&lt;br&gt;Branche Lorum-Margerie]
  F1[René Auguste&lt;br&gt;1886‑1886]
  F2[Marguerite Marie&lt;br&gt;1888‑1977]
  F3[Fernande Marie Renée Marguerie&lt;br&gt;1889‑1930&lt;br&gt;**Internée, décédée à 41 ans**]
  F4[Yves Max Marie Augustin&lt;br&gt;1895‑1914&lt;br&gt;**Mort à 19 ans, probablement au front**]
  Mariage1[Marié le 10 septembre 1894, Bar-le-Duc]
  %% Parents
  P1 --&gt; Mariage1
  P2 --&gt; Mariage1
  Mariage1 --&gt; F1
  Mariage1 --&gt; F2
  Mariage1 --&gt; F3
  Mariage1 --&gt; F4

  %% Mariage et descendance
  M1[Charles Léon René Anchier&lt;br&gt;1886‑1936&lt;br&gt;**Peintre**]
  F3 --&gt; U1[Mariage en 1914]
  M1 --&gt; U1
  U1 --&gt; E1[Marguerite Anchier &lt;br&gt;1916-1955]
  U1 --&gt; E2[Marie-Thérèse Anchier&lt;br&gt;1921‑2015&lt;br&gt;**Couturière**]
  U1 --&gt; E3[Henri Anchier&lt;br&gt;1923‑1939]
</pre>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-arbre-fernande-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.2: Branche de Fernande Marie Renée Marguerie (1889–1930) à Bar-le-Duc
</figcaption>
</figure>
</div>
</div>
</div>
<p>Fernande Marie Renée Marguerie est née à Bar-le-Duc le 22 décembre 1889, un dimanche. Fernande était la troisième d’une fratrie de quatre enfants: René Auguste (mort en bas âge en 1886), Marguerite Marie (1888–1977), elle-même (1889–1930), et Yves Max Marie Augustin, mort à 19 ans en 1914, probablement au front.</p>
<p>Sa mère, <strong>Eugénie Julie Marie Hacquin</strong> (1869–1895), est <strong>morte très jeune</strong>, le 15 février 1895, à 26 ans seulement, quinze jours après avoir donné naissance à son quatrième enfant. <strong>Fernande</strong> avait alors <strong>six ans</strong>. Son père, <strong>René Alexandre Marguerie</strong> (1864–1898), marchand de vin, décède trois ans plus tard. Il appartenait à une <strong>famille aisée et cultivée</strong>, issue de la branche <strong>Lorum-Margerie</strong>, où l’on retrouve plusieurs figures d’intellectuels.</p>
<p>Elle se marie en janvier 1914 avec Charles Léon René Anchier, peintre, avec qui elle a trois enfants: Marguerite, Marie-Thérèse (ma grand mère) et Henri. Vraisemblablement <strong>atteinte de troubles bipolaires</strong> sévères, elle est internée une première fois en 1921, peu après la naissance de sa fille Marie-Thérèse. Internée à nouveau en 1923, suite à la naissance de son fils Henri, elle ne quittera plus l’asile, où elle décède en août 1930, à seulement 41 ans.</p>
<p>Ma grand-mère Marie-Thérèse parlait peu de sa «pauvre maman», qu’elle n’a connue que durant ses deux premières années de vie. Lorsque les enfants de René demandaient à voir leur mère, il leur répondait que cela les ferait trop souffrir de voir dans quel état elle était. De cette mère disparue trop tôt, elle ne devait conserver aucun souvenir réel, seulement l’ombre d’une absence.</p>
<section id="linternement-de-fernande" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="linternement-de-fernande"><span class="header-section-number">6.2.1</span> L’internement de Fernande</h3>
<p>Dès l’été 1921 (<a href="Documents-transcriptions.html#internement-fernande">voir absolument les documents originaux et leur transcription</a>), quelques semaines après la naissance de Marie-Thérèse, Fernande manifeste une mélancolie marquée par des angoisses mystiques et un sentiment de culpabilité aigu. Son beau-père, Charles Anchier, demande son admission à l’asile de Fains le 26 août 1921. Le médecin de famille, peut être membre de la famille (Dr G. Lorum) parle d’un état anxieux, de crise mystique, de prières à genoux, d’un besoin de pénitence, et d’une peur d’être excommuniée. Elle est internée quelques mois, puis ressort en décembre dans un état jugé à peine amélioré.</p>
<p>Mais l’équilibre reste fragile. Après la naissance de son fils Henri en 1923, une nouvelle crise la conduit à être admise le 4 décembre 1923, cette fois à la demande de son mari. Le diagnostic est sévère : psychose discordante, catatonie, mutisme, gestes stéréotypés, violence soudaine. L’hospitalisation durera jusqu’à sa mort en août 1930.</p>
<p>Les rapports médicaux annuels dressent un tableau poignant de son quotidien : mutisme profond, passivité, parfois des épisodes de violence brutale ou de panique. Elle ne communique plus, reste enfermée dans un monde inaccessible. La maladie semble avoir effacé peu à peu toute trace de lien au monde.</p>
<p>À l’époque, aucun <strong>thymorégulateur</strong> (stabilisateur de l’humeur) n’était encore disponible, notamment <strong>le lithium</strong>, qui deviendra pourtant le traitement de référence pour prévenir les rechutes de la bipolarité. Son histoire médicale s’étend sur plus d’un siècle :</p>
<ul>
<li><strong>Milieu du XIXᵉ siècle</strong> : des psychiatres comme Carl Lange au Danemark et William A. Hammond à New York expérimentent des <strong>sels de lithium</strong> contre la manie, sur plusieurs milliers de patients;</li>
<li><strong>1948–1949</strong> : l’Australien <a href="https://fr.wikipedia.org/wiki/John_Cade"><strong>John Cade</strong></a> découvre que le carbonate de lithium possède d’évidentes <strong>propriétés stabilisatrices de l’humeur</strong>, et publie ses travaux en 1949;</li>
<li><strong>1954</strong> : le psychiatre danois <a href="https://en.wikipedia.org/wiki/Mogens_Schou?utm_source=chatgpt.com"><strong>Mogens Schou</strong></a> conforte ces conclusions via une <strong>étude en double aveugle contrôlée</strong>, confirmant l’efficacité du lithium en prophylaxie;</li>
<li><strong>Années 1960–1970</strong> : le lithium entre progressivement dans les protocoles cliniques. Il obtient une <strong>validation de la FDA en 1970</strong> aux États-Unis, devenant le 50ᵉ médicament autorisé pour la bipolarité.</li>
</ul>
<p>Sur plus d’un siècle, le lithium s’est affirmé comme le <strong>premier stabilisateur de l’humeur véritablement efficace</strong>, transformant radicalement la prise en charge des troubles bipolaires — bien que, à l’époque où Fernande est tombée malade, aucun de ces traitements n’existait encore.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copié");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copié");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Gillet-Anchier.html" class="pagination-link" aria-label="Marie Gillet (1852–1941) et Charles Anchier (1852–1935), et leurs enfants">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Marie Gillet (1852–1941) et Charles Anchier (1852–1935), et leurs enfants</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Documents-transcriptions.html" class="pagination-link" aria-label="Documents et transcriptions">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Documents et transcriptions</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>